services:
  web-dashboard:
    image: yearly-finances-dashboard:latest
    container_name: yearly_finances_dashboard
    build:
      context: .
      dockerfile: YearlyFinances.Dashboard/Dockerfile
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MariaDbConnection=Server=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Uid=${DB_USER};Pwd=${DB_PASS};
